In [1]:
import torch
import torch.nn as nn

In [11]:
w = torch.empty(5, 3)
w

tensor([[-7.0276e+28,  3.3498e-41, -5.2798e+28],
        [ 3.3498e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  7.0065e-45],
        [ 0.0000e+00,  1.4013e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  6.8664e-44]])

In [12]:
nn.init.orthogonal_(w)
w

tensor([[-0.1489,  0.2952, -0.1996],
        [-0.4786, -0.5457,  0.3294],
        [-0.5935, -0.1684, -0.7417],
        [-0.1611, -0.4290,  0.3548],
        [-0.6087,  0.6346,  0.4191]])

In [13]:
w.shape

torch.Size([5, 3])

In [14]:
# Compute dot products between all pairs of columns
# For orthogonal columns, we want w_t @ w to be identity matrix
w_t = w.t()
dot_products = torch.mm(w_t, w)  # (5x3) @ (3x5) -> (5x5)

# The diagonal should be ~1 (vector norms) and off-diagonal elements should be ~0
print("Dot products between columns:")
print(dot_products)

# Verify orthogonality - off-diagonal elements should be close to 0
is_orthogonal = torch.allclose(dot_products, torch.eye(w.size(1)), atol=1e-6)
print("\nColumns are orthogonal:", is_orthogonal)

Dot products between columns:
tensor([[ 1.0000e+00, -5.3484e-08,  1.7945e-08],
        [-5.3484e-08,  1.0000e+00, -2.4658e-08],
        [ 1.7945e-08, -2.4658e-08,  1.0000e+00]])

Columns are orthogonal: True
